### ISSUE TITLE
Q..

### ISSUE THREAD

**Issue by arsham6ix** [un4ckn0wl3z/CSO2-Launcher-fixed#1]
Hello, thanks for your work

Can get a global server ip?
and
Can run a private server ( like a local server )

**Comment by un4ckn0wl3z** [comment]
> Hello, thanks for your work
> 
> Can get a global server ip?
> and
> Can run a private server ( like a local server )

Hi 

You need to deploy this private server

https://github.com/L-Leite/cso2-master-server

It is already bundle with docker compose. It is best way to run this server.

PS. This private server only work on LAN or VPN only. Try to setup your zerotier or RAdmin.

Now I deploy this server files on VPS and play with my friends without problem

By using this client 
https://drive.google.com/file/d/1-Jfu2NAonTR_uJG3l7rYUsS2gs-ORRW2/view

With my edited launcher.

**Comment by arsham6ix** [comment]
![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/d13b30f8-c2d3-4298-9bcf-d3d638a5fc7f)

And, How can create a user?

**Comment by un4ckn0wl3z** [comment]
> ![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/d13b30f8-c2d3-4298-9bcf-d3d638a5fc7f)
> 
> And, How can create a user?

Browse your [http://server_ip:8080] for register user

**Comment by un4ckn0wl3z** [comment]
> ![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/d13b30f8-c2d3-4298-9bcf-d3d638a5fc7f)
> 
> And, How can create a user?

If you need to play with your friends. You try to install zerotier vpn client on your vps and both on your PC . Simulating LAN network for all connections can reach others.

**Comment by un4ckn0wl3z** [comment]
> ![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/d13b30f8-c2d3-4298-9bcf-d3d638a5fc7f)
> 
> And, How can create a user?

This server not work on public IP.
Join my discord if you wanna join my server for test https://discord.com/invite/DM9WWUJFxy

**Comment by arsham6ix** [comment]
> > ![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/d13b30f8-c2d3-4298-9bcf-d3d638a5fc7f)
> > And, How can create a user?
> 
> Browse your [http://server_ip:8080] for register user

![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/1efc731b-6bf8-4b7e-8711-56a6268e563b)
 8081 is my port

**Comment by un4ckn0wl3z** [comment]
> > > ![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/d13b30f8-c2d3-4298-9bcf-d3d638a5fc7f)
> > > And, How can create a user?
> > 
> > Browse your [http://server_ip:8080] for register user
> 
> ![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/1efc731b-6bf8-4b7e-8711-56a6268e563b)
>  8081 is my port

It's maybe. Depend on the docker compose you executed.

**Comment by arsham6ix** [comment]
> If you need to play with your friends. You try to install zerotier vpn client on your vps and both on your PC . Simulating LAN network for all connections can reach others.

I joined

**Comment by arsham6ix** [comment]
Server
![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/66e8b9a5-cf1d-4d90-8efe-f490904d75fc)
Webiste
![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/18f3576b-080b-4701-a845-33f4d596f80d)
My Windows
![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/ea84c156-6212-4796-b66e-d1172631a433)

**Comment by arsham6ix** [comment]
Now i need add my public ip address to ip.txt?
![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/facea6ec-f5fd-450c-8f93-6bd855aa1a61)

**Comment by arsham6ix** [comment]
I can see my clients
![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/78823c47-4e0a-41d8-abe3-d5e60dd77e29)

**Comment by arsham6ix** [comment]
> Now i need add my public ip address to ip.txt? ![image](https://user-images.githubusercontent.com/89599368/275337885-facea6ec-f5fd-450c-8f93-6bd855aa1a61.png)

![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/1ba79e72-bf2e-4a4f-8650-e3792325b12b)

**Comment by arsham6ix** [comment]
Done

**Comment by un4ckn0wl3z** [comment]
> > Now i need add my public ip address to ip.txt? ![image](https://user-images.githubusercontent.com/89599368/275337885-facea6ec-f5fd-450c-8f93-6bd855aa1a61.png)
> 
> ![image](https://github.com/un4ckn0wl3z/CSO2-Launcher-fixed/assets/89599368/1ba79e72-bf2e-4a4f-8650-e3792325b12b)
> 
Ip in this file is game server ip. It same with game register ip (10.186.55.3)

**Comment by h4rdl0ckl3z** [comment]
get global server ip from radmin vpn

**Comment by arsham6ix** [comment]
Can add new characters?

**Comment by un4ckn0wl3z** [comment]
Closed
